# Generated by Django 5.2.3 on 2025-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(blank=True, default=models.IntegerField(blank=True, default=1), null=True),
        ),
    ]
